### ISSUE TITLE
[Umbrella]: Sidebar Component

### ISSUE THREAD

**Issue by behzad888** [reactx/reactx#1]
### Touch Support
  - [ ] Cross browser and device/modality testing.

###  Drag Support
 - [ ] implement DragPreview and determine types

### Documentation
  - [ ] Add CodeSandbox Sample
  - [ ] Add Readme
  - [ ] Add to Storybook
  - [ ] Add to Playground
  - [ ] Blog

### Unit Tests
  - [ ] onTouchMove
  - [ ] onTouchStart
  - [ ] onTouchEnd
  - [ ] onTouchCancel
  - [ ] onOverlayClick
  - [ ] onDock
  - [ ] onOpen
  - [ ] onClose
  - [ ] onScroll
  - [ ] pull right for RTL Support
