### ISSUE TITLE
[Umbrella]: Add Slider Component

### ISSUE THREAD

**Issue by behzad888** [reactx/reactx#16]
### Documentation
  - [ ] Add CodeSandbox Sample
  - [ ] Add Readme
  - [ ] Add to Storybook
  - [ ] Add to Playground
  - [ ] Blog
