### ISSUE TITLE
[Umbrella]: Collapse Component

### ISSUE THREAD

**Issue by behzad888** [reactx/reactx#2]
- [ ] Support for animation systems such as `react-transition-group`
 - [ ] Support for ReactMotion
 - [ ] Support for pure javascript transitions
 - [ ] Support for RN, Electron 
 - [x] Determine Types
      ``` WAITING | RESIZING | RESTING | IDLING ```

### Documentation
  - [ ] Add CodeSandbox Sample
  - [ ] Add Readme
  - [ ] Add to Storybook
  - [ ] Add to Playground
  - [ ] Blog
