### ISSUE TITLE
[Umbrella] : Modal Component

### ISSUE THREAD

**Issue by behzad888** [reactx/reactx#20]
### Documentation
  - [ ] Add CodeSandbox Sample
  - [ ] Add Readme
  - [ ] Add to Storybook
  - [ ] Add to Playground
  - [ ] Blog
